### ISSUE TITLE
WG installation failed

### ISSUE THREAD

**Issue by iAmateur** [Fruxlabs/wireguard-roadwarrior#2]
Error - E: Unable to locate package wireguard

**Comment by eshanaswar** [comment]
On which OS are you running the script?

**Comment by iAmateur** [comment]
Ubuntu 18.04.1 (desktop)

**Comment by iAmateur** [comment]
A little more information:
Press any key to continue...
Hit:1 http://us.archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:3 http://deb.debian.org/debian unstable InRelease [237 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Err:3 http://deb.debian.org/debian unstable InRelease
  The following signatures couldn't be verified because the public key is not av                                              ailable: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY 04EE723                                              7B7D453EC
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian unstable InRelease: The following sig                                              natures couldn't be verified because the public key is not available: NO_PUBKEY                                               8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY 04EE7237B7D453EC
E: The repository 'http://deb.debian.org/debian unstable InRelease' is not signe                                              d.
N: Updating from such a repository can't be done securely, and is therefore disa                                              bled by default.
N: See apt-secure(8) manpage for repository creation and user configuration deta                                              ils.
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package wireguard

**Comment by eshanaswar** [comment]
Currently the script supports Debian system only. You can try adding the below commands directly in your terminal and re run the script again. 
```
$ sudo add-apt-repository ppa:wireguard/wireguard
$ sudo apt-get update
$ sudo apt-get install wireguard
```

Also, at first delete the Debian repository (`deb http://deb.debian.org/debian/ unstable main`) added by the script from the file: `/etc/apt/sources.list.d/unstable.list`
and the lines containing 
```
Package: *
Pin: release a=unstable
Pin-Priority: 90
```
from `/etc/apt/preferences.d/limit-unstable`
Note: The script is not tested on Ubuntu environment.

**Comment by eshanaswar** [comment]
Please re-open if the issue is not solved

**Comment by wangjing1215** [comment]
> Error - E: Unable to locate package wireguard

how to deal?

**Comment by eshanaswar** [comment]
> > Error - E: Unable to locate package wireguard
> 
> how to deal?

Which OS are you using?

**Comment by sowmyakavali** [comment]
> > > Error - E: Unable to locate package wireguard
> > 
> > 
> > how to deal?
> 
> Which OS are you using?

ubuntu 18.04

**Comment by Closty** [comment]
Firstly, 
add
`deb http://deb.debian.org/debian buster-backports main`
to your /etc/apt/sources.list (or add a new file with the ".list" extension to /etc/apt/sources.list.d/).
```
apt-get update
apt-get install wireguard/buster-backports
```

**Comment by Lvellios** [comment]
> 首先， 添加 `deb http://deb.debian.org/debian buster-backports main` 到您的 /etc/apt/sources.list（或将扩展名为“.list”的新文件添加到 /etc/apt/sources.list.d/）。
> 
> ```
> apt-get update
> apt-get install wireguard/buster-backports
> ```

its helpful, thanks
