### ISSUE TITLE
Debian 9: no connection after restart 

### ISSUE THREAD

**Issue by Hobbabobba** [Fruxlabs/wireguard-roadwarrior#5]
installed the script on a fresh Debian 9, connection from client to server works fine. after i reboot the debian 9 vm (vpn server) the client doesn´t work anymore (client app on Android shows no error, just no transfer of data through the tunnel).
if i add a new client it works perfect again - until the next reboot.

log file of client: https://pastebin.com/1WkjR7Ki

**Comment by eshanaswar** [comment]
Yes, Currently the script don't save the config on restart. You can re-run the script to add another user and can access the VPN.

**Comment by Hobbabobba** [comment]
any chance to add this functionality?

**Comment by eshanaswar** [comment]
Yes, but after Wireguard gets a stable release for Debian.

**Comment by eshanaswar** [comment]
Mean while you can have a workaround. 
Get the output of the command `wg show`
And add it to the `/etc/wireguard/wg.conf` file as per below parameters

```
[Peer]
PublicKey = **Public key for peer from the wg show command**
AllowedIPs = ** Allowed IP for peer from the wg show command** 
```

and restart Wireguard 

```
wg-quick down wg0
wg-quick up wg0
```

**Comment by Hobbabobba** [comment]
works! thx!

another (silly?) question: if i add another client/peer, i need to add this data to the `wg.conf` file, too?

**Comment by eshanaswar** [comment]
Unfortunately YES as of now. 

You can just add another using the script and update its details in the wg.conf file as shown above.
